FROM php:7.2-apache
RUN apt-get update && \
  docker-php-ext-install pdo_mysql mysqli mbstring && \
  a2enmod rewrite

# Composer install
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# RUN php composer-setup.php
# RUN php -r "unlink('composer-setup.php');"
# RUN mv composer.phar /usr/local/bin/composer
# RUN alias composer="php /usr/local/bin/composer/composer.phar"

# Install git for slim/slim-skeleton
# "-y" is solution : Do you want to continue? [Y/n] Abort.
# RUN apt-get install -y git

# Install zip unzip slim/slim-skeleton
# RUN apt-get install -y zip unzip

# Slim Framework install
# RUN composer create-project slim/slim-skeleton messe